

-- Found file: bean.properties 
exec tp_property_comment 'bean.properties', 'isDemo', '# Set this flag to true if deploying on demo.gtnexus.com'  
exec tp_property_comment 'bean.properties', 'infosvcsRootURL', '### Info Services\n# QA/dev: infosvcs\n# production: infosvcs'  


-- Found file: excel.properties 
exec tp_property_comment 'excel.properties', 'XLTemplatePath', '# The default path that contains the template\n# Absolute, or relative to runtime root folder.'  
exec tp_property_comment 'excel.properties', 'XLOrdersTemplatePath', '# The default path that contains the orders template\n# On production this must be <XLTemplatePath dir>\orders. Where\n# XLTemplatePath is above property. All orders excel files should be copied into\n# <XLTemplatePath dir>\orders dir.\n# Absolute, or relative to runtime root folder.'  
exec tp_property_comment 'excel.properties', 'XLDocumentPath', '# The default path that contains generated files\n# Absolute, or relative to runtime root folder.'  
exec tp_property_comment 'excel.properties', 'XLRowCommentHeightMin', '# The number of additional points per line used to increase the row\n# height of the comment cell, and the maximum height of the row.'  
exec tp_property_comment 'excel.properties', 'XLNoFilterCriteriaSelected', '# Specifies the string to be used if a filter criteria is not selected.'  
exec tp_property_comment 'excel.properties', 'XLSuggestedNoOfCharsInTextField', '# Specifies the number of characters in a line for a text based field\n# like comments or pricing instructions. A line will not have exact this\n# many characters as it might cut words into half, but can be at most\n# one word greater than the length specified here.'  
exec tp_property_comment 'excel.properties', 'XLMaxTimeout', '#Specifies the maximum timeout(in secs) to be set for procurement/contract uploads/downloads.(Configurable)'  
exec tp_property_comment 'excel.properties', 'XLDefTimeout', '#Specifies the default timeout(in secs). If you change the timeout in JRun please make a change here also.'  
exec tp_property_comment 'excel.properties', 'XLPlanningMaxExcelActivity', '#the maximum number of downloads and uploads going on a time'  
exec tp_property_comment 'excel.properties', 'XLPlanningMaxErrors', '#the maximum number of errors before validation ends'  
exec tp_property_comment 'excel.properties', 'MAX_SURCHARGES', '#specifies the number of user defined surcharges that can be downloaded.\n#currently implemented for detail downloads.'  
exec tp_property_comment 'excel.properties', 'XLOptimizationMaxLineItems', '#In optimization, this is the maximum number of line items that one can download/upload.\n#Bug46681: Changing the Limit to 390000 from 65000.'  
exec tp_property_comment 'excel.properties', 'XLCompareOFAWithContractLimitLIs', '#This bug is for disabling OFA to contract comparison only for OFAs containing more than X number of line items.'  
exec tp_property_comment 'excel.properties', 'XLSurchargeHeadingCurrency', '# Strings used to apend to the surcharges names to write\n# into the surcharge headings in the excel spread sheet.'  
exec tp_property_comment 'excel.properties', 'XLUserDefNameOS1', '# Specifies the default names for the user defined surcharges in the template.'  
exec tp_property_comment 'excel.properties', 'XLLITermNotSpecifiedDisplayValue', '# Default value to be displayed for LI/PSS Eff/Exp date if not specified in edit downloads (ie download for upload)'  
exec tp_property_comment 'excel.properties', 'XLRTLMQCTemplateFile', '#To upload Tradelanewise MQC's by the shipper'  
exec tp_property_comment 'excel.properties', 'XLREQAffiliateSheet', '#for Affilate'  
exec tp_property_comment 'excel.properties', 'XLREQCommentsStartCol', '#for Comments'  
exec tp_property_comment 'excel.properties', 'XLRESCarrierSheetEstVol', '#for displayin Est Vol on carrier side'  
exec tp_property_comment 'excel.properties', 'XLRESOFCCapComTemplate', '#CapCom of carrier response'  
exec tp_property_comment 'excel.properties', 'XLREQRequest', '# Contract request cell'  
exec tp_property_comment 'excel.properties', 'XLREQCustomer', '# Customer cell'  
exec tp_property_comment 'excel.properties', 'XLREQTotalMQC', '# MQC in case of Contracts and Total estimated in case of a quotes.'  
exec tp_property_comment 'excel.properties', 'XLREQComments', '# Comments Cell'  
exec tp_property_comment 'excel.properties', 'XLREQTerm', '# Term'  
exec tp_property_comment 'excel.properties', 'XLREQPricingInstruction', '#Shipper's pricing instructions'  
exec tp_property_comment 'excel.properties', 'XLREQFilterCommodity', '# Cells indicating filter criteria used in RFC/RFQ'  
exec tp_property_comment 'excel.properties', 'XLREQAirFilterCommodity', '# Cells indicating filter criteria used in RFC/RFQ for AIR'  
exec tp_property_comment 'excel.properties', 'XLREQSurcharge1', '# Surcharge heading cells'  
exec tp_property_comment 'excel.properties', 'XLRSurchargeHeading', '# Specifies the leftmost cell of the surcharge heading format in the menu sheet.'  
exec tp_property_comment 'excel.properties', 'XLRSurchargeHeadingAir', '# I use B14 instead of A14 here, because the read-only comment would otherwise be copied as well!'  
exec tp_property_comment 'excel.properties', 'XLREQCounteredComment', '# Specifies the cell where a countered comment column's heading will be written.'  
exec tp_property_comment 'excel.properties', 'XLREQColCounteredComment', '# Specifies the column where countered response's comments will be written.'  
exec tp_property_comment 'excel.properties', 'XLREQCounteredCommentFormat', '# Specifies the leftmost cell of the countered comment heading format in the\n# menu sheet.'  
exec tp_property_comment 'excel.properties', 'XLREQColCounteredCommentWidth', '# Specifies the width of Shipper comment column in terms of number of characters\n# This column is used only in case of countered responses.'  
exec tp_property_comment 'excel.properties', 'XLDRAStartRow', '# for carrier worksheet'  
exec tp_property_comment 'excel.properties', 'XLDRAAffiliateStartRow', '#for Affilate worksheet'  
exec tp_property_comment 'excel.properties', 'XLDRACommentsStartRow', '#for Comments worksheet'  
exec tp_property_comment 'excel.properties', 'XLDRADefNameOS1', '# Specifies the default names for the user defined surcharges in the template.'  
exec tp_property_comment 'excel.properties', 'XLDRASurchargeHeadingCurrency', '# String used to apend to the surcharges names to write\n# into the surcharge headings in the excel spread sheet.'  
exec tp_property_comment 'excel.properties', 'XLDRARequest', '# Heading cells'  
exec tp_property_comment 'excel.properties', 'XLDRAFilterCommodity', '# Cells indicating filter criteria used.'  
exec tp_property_comment 'excel.properties', 'XLDRACSUnfinishedRates', '# Constants related to completion status strings'  
exec tp_property_comment 'excel.properties', 'XLDRACSShipperCounters', '# Constants related to countered status strings'  
exec tp_property_comment 'excel.properties', 'XLDRASurcharge1', '# Surcharge heading cells for Draft request download, this\n# specifies the first heading cells (currency) of the four\n# headings.'  
exec tp_property_comment 'excel.properties', 'XLDRACounteredComment', '# Specifies the cell where a countered comment column's heading will be written.'  
exec tp_property_comment 'excel.properties', 'XLDRAColCounteredComment', '# Specifies the column where countered response's comments will be written.'  
exec tp_property_comment 'excel.properties', 'XLDRACounteredCommentFormat', '# Specifies the leftmost cell of the countered comment heading format in the\n# menu sheet.'  
exec tp_property_comment 'excel.properties', 'XLDRAColCounteredCommentWidth', '# Specifies the width of Shipper comment column in terms of number of characters\n# This column is used only in case of countered responses.'  
exec tp_property_comment 'excel.properties', 'XLDRAColumntostartcomment', '# Columns for comments worksheet'  
exec tp_property_comment 'excel.properties', 'XLDRAColumntostart', '# Columns for affiliate worksheet'  
exec tp_property_comment 'excel.properties', 'XLDRACelltostartPricingInstruction', '# Columns for pricing instructions worksheet'  
exec tp_property_comment 'excel.properties', 'XLDRALineItemID', '# Columns for the carrier worksheet.'  
exec tp_property_comment 'excel.properties', 'XLDRAColCarrierFlexField1', '# Specifies the first flex field column.\n# Other flex field columns are calculated relative to this column.'  
exec tp_property_comment 'excel.properties', 'XLDRAColCarrierOS1Value', '#surcharge columns'  
exec tp_property_comment 'excel.properties', 'XLDRAVariableSurchargeHeadingOceanStartCell', '# Specifies the location of the first surcharge heading cell when using variable surcharges.'  
exec tp_property_comment 'excel.properties', 'XLDRAIOStartRow', '# for carrier worksheet'  
exec tp_property_comment 'excel.properties', 'XLDRAIODefNameOS1', '# Specifies the default names for the user defined surcharges in the template.'  
exec tp_property_comment 'excel.properties', 'XLDRAIOSurchargeHeadingCurrency', '# String used to apend to the surcharges names to write\n# into the surcharge headings in the excel spread sheet.'  
exec tp_property_comment 'excel.properties', 'XLDRAIORequest', '# Heading cells'  
exec tp_property_comment 'excel.properties', 'XLDRAIOFilterTradeRegion', '# Cells indicating filter criteria used.'  
exec tp_property_comment 'excel.properties', 'XLDRAIOCSUnfinishedRates', '# Constants related to completion status strings'  
exec tp_property_comment 'excel.properties', 'XLDRAIOCSShipperCounters', '# Constants related to counter status strings'  
exec tp_property_comment 'excel.properties', 'XLDRAIOSurcharge1', '# Surcharge heading cells for Draft request download, this\n# specifies the first heading cells (currency) of the four\n# headings.'  
exec tp_property_comment 'excel.properties', 'XLDRAIOCounteredComment', '# Specifies the cell where a countered comment column's heading will be written.'  
exec tp_property_comment 'excel.properties', 'XLDRAIOColCounteredComment', '# Specifies the column where countered response's comments will be written.'  
exec tp_property_comment 'excel.properties', 'XLDRAIOCounteredCommentFormat', '# Specifies the leftmost cell of the countered comment heading format in the\n# menu sheet.'  
exec tp_property_comment 'excel.properties', 'XLDRAIOColCounteredCommentWidth', '# Specifies the width of Shipper comment column in terms of number of characters\n# This column is used only in case of countered responses.'  
exec tp_property_comment 'excel.properties', 'XLDRAIOLineItemID', '# Columns for the carrier worksheet.'  
exec tp_property_comment 'excel.properties', 'XLDRAIOColOriginMode', '#XLDRAIOColOriginPortOfLoading=F\n#XLDRAIOColOriginRouting=G'  
exec tp_property_comment 'excel.properties', 'XLDRAIOColDestinationLoad', '#XLDRAIOColDestinationPortOfDischarge=L\n#XLDRAIOColDestinationRouting=M\n#XLDRAIOColDestinationMode=N'  
exec tp_property_comment 'excel.properties', 'XLDRAIOColCarrierOS1Value', '#surcharge columns'  
exec tp_property_comment 'excel.properties', 'XLIOColCarrierSurchargeHeadingStartCell', '# Surcharge heading cells for Draft request download, this\n# specifies the first heading cells (currency) of the four\n# headings.'  
exec tp_property_comment 'excel.properties', 'XLRAirOFCTemplateFile', '#Template for Air OFC Excel download'  
exec tp_property_comment 'excel.properties', 'XLRESCommentsStartRow', '# for Comments worksheet'  
exec tp_property_comment 'excel.properties', 'XLRESRequest', '# Contract request cell'  
exec tp_property_comment 'excel.properties', 'XLRESCustomerLabel', '# Customer/Carrier cell label'  
exec tp_property_comment 'excel.properties', 'XLRESCustomer', '# Customer cell'  
exec tp_property_comment 'excel.properties', 'XLRESTotalMQC', '# MQC in case of OFC and Total estimated in case of a quotes.'  
exec tp_property_comment 'excel.properties', 'XLRESComments', '# Comments Cell'  
exec tp_property_comment 'excel.properties', 'XLRESTerm', '# Term'  
exec tp_property_comment 'excel.properties', 'XLRESLeadTimeForBooking', '#Lead Time for Booking'  
exec tp_property_comment 'excel.properties', 'XLRESFilterCommodity', '# Cells indicating filter criteria used in response.'  
exec tp_property_comment 'excel.properties', 'XLRESColCommodity', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLRESColCarrierSFTimes', '#new columns for sailing frequency.(for OFC)'  
exec tp_property_comment 'excel.properties', 'XLRESColFlexField1', '# Specifies the first flex field column.\n# Other flex field columns are calculated relative to this column.'  
exec tp_property_comment 'excel.properties', 'XLRESColCarrierOS1Value', '#surcharge columns - FIXME MW why does the ResponseWriter not use XLRESColCarrierSurchargeHeadingFormat for getting the'  
exec tp_property_comment 'excel.properties', 'XLRESColCarrierSurchargeHeadingFormat', '# Specifies the leftmost cell of the surcharge header'  
exec tp_property_comment 'excel.properties', 'XLRESAirFilterCommodity', '# Columns related to Excel for Air OFC'  
exec tp_property_comment 'excel.properties', 'XLEVTemplateFileOpt', '# Specifies the template file name used for generating the estimated volume\n# excel sheet. This template should be present in the path specified in the\n# property "XLTemplatePath" above.'  
exec tp_property_comment 'excel.properties', 'XLEVReadMeSheet', '# Specifies the sheet numbers.'  
exec tp_property_comment 'excel.properties', 'XLEVStartRow', '# Speicfies the start/end row and column where processing can start. These\n# properties will be used as a string (ie like 16 in B16), so is not\n# substracted by 1. If this has to be used as a integer in Formula one, this\n# value should be substracted by 1.'  
exec tp_property_comment 'excel.properties', 'XLEVRequestIdHidden', '# Specifies the cell where request id is written into. This cell/row is\n# hidden in when the excel file is downloaded, so user does not see this\n# number. Request id is written in this cell when the response is downloaded\n# and used when that file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLEVRequestSeasonalityHidden', '# Specifies the cell where request seasonality is written into. This cell/row is\n# hidden in when the excel file is downloaded, so user does not see this\n# number. Seasonality is written in this cell when the response is downloaded\n# and used when that file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLEVRequest', '# Specifies the Heading cells.'  
exec tp_property_comment 'excel.properties', 'XLEVFilterCommodity', '# Cells indicating filter criteria used.'  
exec tp_property_comment 'excel.properties', 'XLEVSummaryTradeLane', '# Columns for the summary sheet'  
exec tp_property_comment 'excel.properties', 'XLEVEstVolID', '# Columns in the Estimated volume sheet'  
exec tp_property_comment 'excel.properties', 'XLCCTemplateFile', '# Specifies the template file name used for generating the capacity commitment\n# excel sheet. This template should be present in the path specified in the\n# property "XLTemplatePath" above.'  
exec tp_property_comment 'excel.properties', 'XLCCReadMeSheet', '# Specifies the sheet numbers.'  
exec tp_property_comment 'excel.properties', 'XLCCMenuSheet', '# Rel 8.0.3 (mthyen) This does not appear to be used anymore so I am reusing the sheet number'  
exec tp_property_comment 'excel.properties', 'XLCCStartRow', '# Speicfies the start/end row and column where processing can start. These\n# properties will be used as a string (ie like 16 in B16), so is not\n# substracted by 1. If this has to be used as a integer in Formula one, this\n# value should be substracted by 1.'  
exec tp_property_comment 'excel.properties', 'XLCCPSSStartRow', '# Speicfies the start/end row and column where processing can start. These\n# properties will be used as a string (ie like 16 in B16), so is not\n# substracted by 1. If this has to be used as a integer in Formula one, this\n# value should be substracted by 1.'  
exec tp_property_comment 'excel.properties', 'XLCCResponseIdHidden', '# Specifies the cell where response id is written into. This cell/row is\n# hidden in when the excel file is downloaded, so user does not see this\n# number. Response id is written in this cell when the response is downloaded\n# and used when that file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLCCResponseSeasonalityHidden', '# Specifies the cell where response seasonality is written into. This cell/row is\n# hidden in when the excel file is downloaded, so user does not see this\n# number. Response seasonality is written in this cell when the response is downloaded\n# and used when that file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLCCRequest', '# Specifies the Heading cells.'  
exec tp_property_comment 'excel.properties', 'XLCCFilterTradeLane', '# Cells indicating filter criteria used.'  
exec tp_property_comment 'excel.properties', 'XLCCCSUnfinishedCapCom', '# Constants related to completion status strings'  
exec tp_property_comment 'excel.properties', 'XLCCColCapComID', '# Columns in the Cap Com volume sheet'  
exec tp_property_comment 'excel.properties', 'XLCCColPSS', '# Columns in the Preferred Service String Cap Com volume sheet'  
exec tp_property_comment 'excel.properties', 'XLOPTICCFormatStartCol', '#Specifies the readonly format that should be copied'  
exec tp_property_comment 'excel.properties', 'XLOPTICCFormatStartRow', '# these row numbers start from zero not one'  
exec tp_property_comment 'excel.properties', 'XLOPTICapComTemplateFile', '# Specifies the template file name used for generating the capacity commitment\n# excel sheet. This template should be present in the path specified in the\n# property "XLTemplatePath" above.'  
exec tp_property_comment 'excel.properties', 'XLOPTICapComReadMeSheet', '# Specifies the sheet numbers.'  
exec tp_property_comment 'excel.properties', 'XLOPTICapComStartRow', '# Speicfies the start/end row and column where processing can start. These\n# properties will be used as a string (ie like 16 in B16), so is not\n# substracted by 1. If this has to be used as a integer in Formula one, this\n# value should be substracted by 1.'  
exec tp_property_comment 'excel.properties', 'XLOPTICCScenarioName', '# Specifies the Heading cells\n# scenario name cell'  
exec tp_property_comment 'excel.properties', 'XLOPTICapComRuleID', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLOPTICCFilterOfcOrContract', '# Cells indicating filter criteria used.'  
exec tp_property_comment 'excel.properties', 'XLOPTIStringCapComStartRow', '# Speicfies the start/end row and column where processing can start. These\n# properties will be used as a string (ie like 16 in B16), so is not\n# substracted by 1. If this has to be used as a integer in Formula one, this\n# value should be substracted by 1.'  
exec tp_property_comment 'excel.properties', 'XLOPTIStringCCScenarioName', '# Specifies the Heading cells\n# scenario name cell'  
exec tp_property_comment 'excel.properties', 'XLOPTIStringCapComContractOFC', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLOPTIStringCapComScenarioIDHidden', '# Specifies the cell where scenario id is hidden'  
exec tp_property_comment 'excel.properties', 'XLOPTICapComTotalNumberOfLIsInFile', '# Specifies the cell where the number of line items in the downloaded file is stored'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyTemplateFile', '# Specifies the template file name used for generating the capacity commitment\n# excel sheet. This template should be present in the path specified in the\n# property "XLTemplatePath" above.'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplySeasonalTemplateFile', '#Release 11.2 Feature13065 Allocation lock Applies only for Flat scenario(Non seasonal).\n#This can be updated with 13 columns for Seasonal scenario.'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyReadMeSheet', '# Specifies the sheet numbers.'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyFormatStartCol', '#Specifies the readonly format that should be copied'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyFormatEndCol', '# Changed from  XLOPTISupplyFormatEndCol=AS to XLOPTISupplyFormatEndCol=AT after adding allocation details'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyFormatStartRow', '# these row numbers start from zero not one'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyScenarioIDHidden', '# Specifies the cell where scenario id is hidden'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyTotalNumberOfLIsInFile', '# Specifies the cell where the number of line items in the downloaded file is stored'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyStartRow', '# Speicfies the start/end row and column where processing can start. These\n# properties will be used as a string (ie like 16 in B16), so is not\n# substracted by 1. If this has to be used as a integer in Formula one, this\n# value should be substracted by 1.'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyScenarioName', '# Specifies the Heading cells\n# scenario name cell'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyFilterCarrier', '# Cells indicating filter criteria'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyScenarioSupplyID', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyOriginCountry', '#XLOPTISupplyOriginState=G'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyDestinationCountry', '#XLOPTISupplyDestinationState=M'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyCanal', '# Added for UC#7057'  
exec tp_property_comment 'excel.properties', 'XLOPTISupplyFlexFldVal1', '# Added for UC#7057 Flex Fields and Custom Fields'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandEstVolume', '#'  
exec tp_property_comment 'excel.properties', 'XLCONVariableSurchargesTemplateFile', '# Template with variable surcharges'  
exec tp_property_comment 'excel.properties', 'XLCONEditVariableSurchargesTemplateFile', '# Template with variable surcharges'  
exec tp_property_comment 'excel.properties', 'XLCONAffiliatesStartRow', '# Specifies affiliates sheet related properties.'  
exec tp_property_comment 'excel.properties', 'XLCONCommentsBlockFormat', '# Specifies comments sheet related properties.'  
exec tp_property_comment 'excel.properties', 'XLCONShipperCommentCellHeight', '# specifies the shipper comment block height'  
exec tp_property_comment 'excel.properties', 'XLDRAIOSurchargeHeadingStartCell', '# Specifies the location of the first surcharge heading cell.'  
exec tp_property_comment 'excel.properties', 'XLCONVariableSurchargeHeadingStartCell', '# Specifies the location of the first surcharge heading cell when using variable surcharges.'  
exec tp_property_comment 'excel.properties', 'XLCONSurchargeHeadingFormat', '# XLDRAVariableSurchargeHeadingStartCell=BC2 not used\n# Specifies the leftmost cell of the surcharge heading format in the menu sheet.'  
exec tp_property_comment 'excel.properties', 'XLCONContractNo', '# this is the refnum of the contract'  
exec tp_property_comment 'excel.properties', 'XLCONContractId', '# this is the id of the contract'  
exec tp_property_comment 'excel.properties', 'XLCONOrgFlexField1', '# Specifies the first org. flex field cell.\n# Other org. flex field cells are calculated relative to this cell.'  
exec tp_property_comment 'excel.properties', 'XLCONFilterCommodity', '# Cells indicating filter criteria used.'  
exec tp_property_comment 'excel.properties', 'XLCONColUniqueNumber', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLCONColFlexField1', '# Specifies the first flex field column.\n# Other flex field columns are calculated relative to this column.'  
exec tp_property_comment 'excel.properties', 'XLCONIOConTemplateFile', '# Specifies the template file name used for generating the contracts excel\n# sheet. This template should be present in the path specified in the\n# property "XLTemplatePath" above.\n# This template is used for draft and non-draft download'  
exec tp_property_comment 'excel.properties', 'XLCONPIOConTemplateFile', '# These are the public inland templates'  
exec tp_property_comment 'excel.properties', 'XLCONIOContractSheet', '# Specifies the sheet numbers.'  
exec tp_property_comment 'excel.properties', 'XLCONIOAffiliatesStartRow', '# Specifies affiliates sheet related properties.'  
exec tp_property_comment 'excel.properties', 'XLCONIOCommentsBlockFormat', '# Specifies comments sheet related properties.'  
exec tp_property_comment 'excel.properties', 'XLCONIOShipperCommentCellHeight', '# specifies the shipper comment block height'  
exec tp_property_comment 'excel.properties', 'XLCONIOShipperPriceBasisOffer', '# Specifies the cell to indicate the shipper price basis - do we need this prop'  
exec tp_property_comment 'excel.properties', 'XLCONIOSurchargeHeadingStartCell', '# Specifies the location of the first surcharge heading cell.'  
exec tp_property_comment 'excel.properties', 'XLCONIOEditSurchargeHeadingStartCell', '# Specifies the location of the first surcharge heading cell for editing of contract inlands.'  
exec tp_property_comment 'excel.properties', 'XLCONIOSurchargeHeadingFormat', '# Specifies the leftmost cell of the surcharge heading format in the menu sheet.'  
exec tp_property_comment 'excel.properties', 'XLCONIOContractNo', '#XLCONIOContractNo=B3'  
exec tp_property_comment 'excel.properties', 'XLCONIOColUniqueNumber', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLCONIOColFromLoad', '#XLCONIOColMQCPerTracdeLane=D\n#XLCONIOColFromLocation=E\n#XLCONIOColFromService=F\n# 7.5. - do not use these columns\n# XLCONIOColFromPort=G\n# XLCONIOColFromRouting=H\n#XLCONIOColFromMode=G'  
exec tp_property_comment 'excel.properties', 'XLCONIOColToUnload', '#XLCONIOColToLocation=I\n#XLCONIOColToService=J\n# XLCONIOColToPort=M\n# XLCONIOColToRouting=N\n# XLCONIOColToMode=O'  
exec tp_property_comment 'excel.properties', 'XLOPTIColOFCConNum', '# Specifies the columns of various data elements.\n# Scenario result columns'  
exec tp_property_comment 'excel.properties', 'XLOPTIColDestinationRegion', '#XLOPTIColOrigState=C\n#Destination'  
exec tp_property_comment 'excel.properties', 'XLOPTIColFlexFldVal1', '# Added for UC#7057'  
exec tp_property_comment 'excel.properties', 'XLOPTIColCapComOFCConNum', '# capicity commitment columns'  
exec tp_property_comment 'excel.properties', 'XLOPTIColMQCOFCConNum', '# MQC columns'  
exec tp_property_comment 'excel.properties', 'XLOPTIColTotalMQCOFCConNum', '# Total MQC columns'  
exec tp_property_comment 'excel.properties', 'XLOPTICellCarrierAllocation', '# Specifies the cells where it says if a business rule is applicable.'  
exec tp_property_comment 'excel.properties', 'XLOPTIColCarrierRuleCarrier', '# Columns for carrier rule'  
exec tp_property_comment 'excel.properties', 'XLOPTIColTierRuleCarrier', '# Columns for tier rule'  
exec tp_property_comment 'excel.properties', 'XLOPTIColSelectivityRuleCarrier', '# Columns for selectivity rule'  
exec tp_property_comment 'excel.properties', 'XLOPTIColCarrierTier1', '# carrier tier columns'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandReadmeSheet', '# Specifies the sheet numbers. If the templates are changed, alter these\n# numbers accordingly.'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandFormatStartCol', '#Specifies the readonly format that should be copied'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandFormatEndCol', '# Changed for UC#12124 rel.102 from L to K'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandFormatStartRow', '# these row numbers start from zero not one'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandScenarioIDHidden', '# Specifies the cell where scenario id is hidden'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandTotalNumberOfLIsInFile', '# Specifies the cell where the number of line items in the downloaded file is stored'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandScenarioName', '# Specifies the Heading cells\n# scenario name cell'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandFilterCommodity', '# Cells indicating filter criteria'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandColDemandIDHidden', '# Specifies the columns of various data elements.'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandColOrigCity', '#XLOPTIDemandColTradeLane=D removed for relax tradelane'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandColOrigCountry', '#XLOPTIDemandColOrigState=E'  
exec tp_property_comment 'excel.properties', 'XLOPTIDemandColDestCountry', '#XLOPTIDemandColDestState=I'  
exec tp_property_comment 'excel.properties', 'XLOPTIReportHeadingCellScenarioName', '# Specifies the locations of the header cells, common to both the reports.'  
exec tp_property_comment 'excel.properties', 'XLOPTIWAReportStartRow', '# Speicfies the start/end row and column where processing can start. These\n# properties will be used as a string (ie like 16 in B16), so is not\n# substracted by 1. If this has to be used as a integer in Formula one, this\n# value should be substracted by 1.'  
exec tp_property_comment 'excel.properties', 'XLOPTIODReportCarrierFormatCell', '# Specifies hidden formatting cells.'  
exec tp_property_comment 'excel.properties', 'XLOPTIWAReportDataSheet', '# Specifies the sheet numbers. If the templates are changed, alter these\n# numbers accordingly.'  
exec tp_property_comment 'excel.properties', 'XLOPTIODReportColCommodity', '# Specifies the columns of various data elements for optimal distribution report.'  
exec tp_property_comment 'excel.properties', 'XLOPTIWAReportColCommodity', '# Specifies the columns of various data elements for weighted average report.'  
exec tp_property_comment 'excel.properties', 'XLOFAPricingInsturctionsStartRow', '# for pricing instructions sheet.'  
exec tp_property_comment 'excel.properties', 'XLOFASurcharge1', '# userdefined surcharge name'  
exec tp_property_comment 'excel.properties', 'XLOFASurchargeHeadingCurrency', '# String used to apend to the surcharges names to write\n# into the surcharge headings in the excel spread sheet.'  
exec tp_property_comment 'excel.properties', 'XLOFADefNameOS1', '# Specifies the default names for the user defined surcharges in the template.'  
exec tp_property_comment 'excel.properties', 'XLOFARequest', '# Contract request cell'  
exec tp_property_comment 'excel.properties', 'XLOFACustomer', '# Customer cell'  
exec tp_property_comment 'excel.properties', 'XLOFAContractNumber', '# Contract Number'  
exec tp_property_comment 'excel.properties', 'XLOFAType', '#Type and Event'  
exec tp_property_comment 'excel.properties', 'XLOFAComments', '# Comments Cell'  
exec tp_property_comment 'excel.properties', 'XLOFAColCarrierRespond', '#carrier response part'  
exec tp_property_comment 'excel.properties', 'XLOFADetailPricingInsturctionsStartRow', '# for pricing instructions sheet.'  
exec tp_property_comment 'excel.properties', 'XLOFADetailSurcharge1', '# userdefined surcharge name'  
exec tp_property_comment 'excel.properties', 'XLOFADetailSurchargeHeadingCurrency', '# String used to apend to the surcharges names to write\n# into the surcharge headings in the excel spread sheet.'  
exec tp_property_comment 'excel.properties', 'XLOFADetailDefNameOS1', '# Specifies the default names for the user defined surcharges in the template.'  
exec tp_property_comment 'excel.properties', 'XLOFADetailRequest', '# Contract request cell'  
exec tp_property_comment 'excel.properties', 'XLOFADetailCustomer', '# Customer cell'  
exec tp_property_comment 'excel.properties', 'XLOFADetailType', '#Type and Event'  
exec tp_property_comment 'excel.properties', 'XLOFADetailComments', '# Comments Cell'  
exec tp_property_comment 'excel.properties', 'XLOFADetailColShipperPriceBasisOffer', '#price at offerlevel'  
exec tp_property_comment 'excel.properties', 'XLOFADetailFilterCommodity', '# Cells indicating filter criteria used in OFA'  
exec tp_property_comment 'excel.properties', 'XLOFADetailColCarrierRespond', '#carrier response part'  
exec tp_property_comment 'excel.properties', 'XLCIOFAStartRow', '# Specifies the start row for the carrier sheet.'  
exec tp_property_comment 'excel.properties', 'XLCIOFASurchargeHeadingFormat', '# Location of the heading format in the menu sheet'  
exec tp_property_comment 'excel.properties', 'XLCIOFADefNameOS1', '# Specifies the default names for the user defined surcharges in the template.'  
exec tp_property_comment 'excel.properties', 'XLCIOFASurchargeHeadingCurrency', '# String used to apend to the surcharges names to write\n# into the surcharge headings in the excel spread sheet.'  
exec tp_property_comment 'excel.properties', 'XLCIOFAId', '# the ofa id is used when this file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLCIOFACustomer', '# Customer cell'  
exec tp_property_comment 'excel.properties', 'XLCIOFAConId', '# the contract id of the contract on which this ofa is based on\n# is used when this file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLRFCIOCarrierSheet', '#XLRFCIOReadMeSheet=0'  
exec tp_property_comment 'excel.properties', 'XLRFCIOStartRow', '# Specifies the start/end  row and column where processing can start.'  
exec tp_property_comment 'excel.properties', 'XLRFCIOCommentsStartRow', '#for Comments worksheet'  
exec tp_property_comment 'excel.properties', 'XLRFCIORequest', '# Contract request cell'  
exec tp_property_comment 'excel.properties', 'XLRFCIOCustomer', '# Customer cell'  
exec tp_property_comment 'excel.properties', 'XLRFCIOTerm', '# Request Term'  
exec tp_property_comment 'excel.properties', 'XLRFCIOFilterTradeRegion', '# Cells indicating filter criteria used in RFC Inland/Outports'  
exec tp_property_comment 'excel.properties', 'XLRFCIOLineItemID', '# in this column, the line item id is hidden.'  
exec tp_property_comment 'excel.properties', 'XLRFCIOColFromLocationMode', '# XLRFCIOColFromLocationPort=F\n# XLRFCIOColFromLocationRouting=G'  
exec tp_property_comment 'excel.properties', 'XLRFCIOColToLocationLoad', '# XLRFCIOColToLocationPort=L\n# XLRFCIOColToLocationRouting=M\n# XLRFCIOColToLocationMode=N'  
exec tp_property_comment 'excel.properties', 'XLRFCIOColTargetprice', '#XLRFCIOColEquipmentShipperOwn=L'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFAStartRow', '# Specifies the start row for the carrier sheet.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFASurcharge1', '# userdefined surcharge's header cell. This will have the cell name of the first\n# column, ie the currency.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADefNameOS1', '# Specifies the default names for the user defined surcharges in the template.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFASurchargeHeadingCurrency', '# String used to apend to the surcharges names to write\n# into the surcharge headings in the excel spread sheet.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFAIdHidden', '# the ofa id is hidden in this cell, is used when this file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFAConIdHidden', '# the contract id of the contract on which this ofa is based on is hidden in this cell,\n# is used when this file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFARequest', '# Contract request cell'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFACustomer', '# Customer cell'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFAFilterTradeRegion', '# Cells indicating filter criteria used in Carrier Initiated OFA'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFALineItemID', '# in this column, the line item id is hidden. Will be used by upload functionality.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFAColFromLocationMode', '# XLIOCIOFAColFromLocationPort=F\n# XLIOCIOFAColFromLocationRouting=G'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFAColToLocationLoad', '# XLIOCIOFAColToLocationPort=L\n# XLIOCIOFAColToLocationRouting=M\n# XLIOCIOFAColToLocationMode=N'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailStartRow', '# Specifies the start row for the carrier sheet.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailSurcharge1', '# userdefined surcharge's header cell. This will have the cell name of the first\n# column, ie the currency.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailDefNameOS1', '# Specifies the default names for the user defined surcharges in the template.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailSurchargeHeadingCurrency', '# String used to apend to the surcharges names to write\n# into the surcharge headings in the excel spread sheet.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailIdHidden', '# the ofa id is hidden in this cell, is used when this file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailConIdHidden', '# the contract id of the contract on which this ofa is based on is hidden in this cell,\n# is used when this file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailRequest', '# Contract request cell'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailCustomer', '# Customer cell'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailFilterTradeRegion', '# Cells indicating filter criteria used in Carrier Initiated OFA'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailLineItemID', '# in this column, the line item id is hidden. Will be used by upload functionality.'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailColFromLocationMode', '# XLIOCIOFADetailColFromLocationPort=F\n# XLIOCIOFADetailColFromLocationRouting=G'  
exec tp_property_comment 'excel.properties', 'XLIOCIOFADetailColToLocationLoad', '# XLIOCIOFADetailColToLocationPort=L\n# XLIOCIOFADetailColToLocationRouting=M\n# XLIOCIOFADetailColToLocationMode=N'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailVariableSurchargesTemplateFile', '# Template with variable surcharges'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailAirTemplateFile', '# Template for Air OFA excel download'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailStartRow', '# Specifies the start row for the carrier sheet.'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailSurcharge1', '# userdefined surcharge's header cell. This will have the cell name of the first\n# column, ie the currency.'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailDefNameOS1', '# Specifies the default names for the user defined surcharges in the template.'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailSurchargeHeadingCurrency', '# String used to apend to the surcharges names to write\n# into the surcharge headings in the excel spread sheet.'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailSurchargeHeadingBasis', '# XLCIOFADetailSurchargeHeadingInclInNet=Included in Net Freight Calculation'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailIdHidden', '# the ofa id is hidden in this cell, is used when this file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailConIdHidden', '# the contract id of the contract on which this ofa is based on is hidden in this cell,\n# is used when this file is uploaded.'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailRequest', '# Contract request cell'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailCustomer', '# Customer cell'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailCellPriceBasisOffer', '#price at offerlevel'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailFilterCommodity', '# Cells indicating filter criteria used in Carrier Initiated OFA'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailAirFilterContractID', '# Cells indicating filter criteria used in Carrier Initiated OFA for Air'  
exec tp_property_comment 'excel.properties', 'XLOFADetailAirFilterServiceLevel', '#service Type and Weight Break'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailLineItemID', '# in this column, the line item id is hidden. Will be used by upload functionality.'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailAirColLineItemID', '# columns in the Air OFA excel sheet'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailColPriorPrefService', '#carrier response part'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailColFlexField1', '# Specifies the first flex field column.\n# Other flex field columns are calculated relative to this column.'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailVariableSurchargeHeadingStartCell', '# Specifies the location of the first surcharge heading cell when using variable surcharges.'  
exec tp_property_comment 'excel.properties', 'XLCIOFADetailAirVariableSurchargeHeadingStartCell', '# Specifies the location of the first surcharge heading cell(for air OFA) when using variable surcharges.'  
exec tp_property_comment 'excel.properties', 'XLMaxFAReportExportTimeout', '#12 hrs time out (secs) set for FA report download'  
exec tp_property_comment 'excel.properties', 'XLAMNDAffiliatesStartRow', '# Specifices affiliates sheet related properties.'  
exec tp_property_comment 'excel.properties', 'XLAMNDSurchargeHeadingFormat', '# Specifies the leftmost cell of the surcharge heading format in the menu sheet.'  
exec tp_property_comment 'excel.properties', 'XLAMNDCommentsBlockFormat', '# Specifices comments sheet related properties.'  
exec tp_property_comment 'excel.properties', 'XLAMNDShipperCommentCellHeight', '# specifies the shipper comment block height'  
exec tp_property_comment 'excel.properties', 'XLAMNDLeadTime', '#XLAMNDTotalMQC=B8'  
exec tp_property_comment 'excel.properties', 'XLAMNDComments', '#XLAMNDAccessDate=B14 - access date is not used in amendments.'  
exec tp_property_comment 'excel.properties', 'XLAMNDColUniqueNumber', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLAMNDColFlexField1', '# Specifies the first flex field column.\n# Other flex field columns are calculated relative to this column.'  
exec tp_property_comment 'excel.properties', 'XLCRSRMaxLineItems', '# Specifies the maximum number of line items that the contract download\n# will read into a excel spread sheet. If the number of line items crosses\n# the limit, the contract writer will throw a exception. The user is displayed\n# a error message thus the user will be forced to further constrain the search\n# so as to get the limit within the given value below.'  
exec tp_property_comment 'excel.properties', 'XLCRSRSurchargeHeadingStartCell', '# Specifies the location of the first surcharge heading cell.'  
exec tp_property_comment 'excel.properties', 'XLCRSRSurchargeHeadingFormat', '# Specifies the leftmost cell of the surcharge heading format in the menu sheet.'  
exec tp_property_comment 'excel.properties', 'XLCRSRColCommodity', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLCRSRColFlexField1', '# Specifies the first flex field column.\n# Other flex field columns are calculated relative to this column.'  
exec tp_property_comment 'excel.properties', 'XLCRSRIOSurchargeHeadingStartCell', '# Specifies the location of the first surcharge heading cell.'  
exec tp_property_comment 'excel.properties', 'XLCRSRIOSurchargeHeadingFormat', '# Specifies the leftmost cell of the surcharge heading format in the menu sheet.'  
exec tp_property_comment 'excel.properties', 'XLCRSRIOColOriginLocation', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLAirSCRSurchargeHeadingStartCell', '# Specifies the location of the first surcharge heading cell.'  
exec tp_property_comment 'excel.properties', 'XLAirSCRSurchargeHeadingFormat', '# Specifies the leftmost cell of the surcharge heading format in the menu sheet.'  
exec tp_property_comment 'excel.properties', 'XLAirSCRColCommodity', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLAirSCRColCarrier', '# Shipper name for carriers, carrier name for shippers'  
exec tp_property_comment 'excel.properties', 'XLAirSCRColCDCN', '# Response ID for offers, Contract CDCN for contracts'  
exec tp_property_comment 'excel.properties', 'XLAirSCRColContractState', '# Offer status for offers, Contract state for contracts'  
exec tp_property_comment 'excel.properties', 'XLAirCRSRColFlexField1', '# Specifies the first flex field column.\n# Other flex field columns are calculated relative to this column.'  
exec tp_property_comment 'excel.properties', 'XLAirSCRColOtherSurchargeValue', '# Specifies the columns for the first user defined surcharge, others are calculated\n# on basis of its relative position with these columns.\n# ! One empty column !'  
exec tp_property_comment 'excel.properties', 'XLAIRCONMaxLineItems', '# Specifies the maximum number of line items that the contract download\n# will read into a excel spread sheet. If the number of line items crosses\n# the limit, the contract writer will throw a exception. The user is displayed\n# a error message thus the user will be forced to further constrain the search\n# so as to get the limit within the given value below.'  
exec tp_property_comment 'excel.properties', 'XLAIRCONCommentsBlockFormat', '# Specifices comments sheet related properties.'  
exec tp_property_comment 'excel.properties', 'XLAIRCONShipperCommentCellHeight', '# specifies the shipper comment block height'  
exec tp_property_comment 'excel.properties', 'XLAIRCONSurchargeHeadingStartCell', '# Speicfies the location of the first surcharge heading cell.\n# Attention!!! The column of this must be the same as XLAIRCONColOtherSurchargeValue below!'  
exec tp_property_comment 'excel.properties', 'XLAIRCONSurchargeHeadingFormat', '# Specifies the leftmost cell of the surcharge heading format in the menu sheet.'  
exec tp_property_comment 'excel.properties', 'XLAIRCONColUniqueNumber', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLDSTemplateID', '# heading cells'  
exec tp_property_comment 'excel.properties', 'XLDSColMaxCopyCellFormat', '# Cell format (highlighting) will be copied upto this column'  
exec tp_property_comment 'excel.properties', 'XLDSColUniqueNumber', '# Columns'  
exec tp_property_comment 'excel.properties', 'XLDraftResponseLegalColumnStarts', '#Legal Names for DraftResponse downloads'  
exec tp_property_comment 'excel.properties', 'XLDraftIOResponseLegalColumnStarts', '#Legal Names for DraftIOResponse downloads'  
exec tp_property_comment 'excel.properties', 'XLCRSRLegalColumnStarts', '#Legal Names for Rates/Contracts Search/Compare downloads'  
exec tp_property_comment 'excel.properties', 'XLAirSCRLegalColumnStarts', '#Legal Names for Air Rates/Contracts Search/Compare downloads'  
exec tp_property_comment 'excel.properties', 'XLResponseLegalColumnStarts', '#Legal Names for Response downloads'  
exec tp_property_comment 'excel.properties', 'XLRequestFooterCenter', '#Legal Names for Request Detail downloads'  
exec tp_property_comment 'excel.properties', 'XLRFCIOLegalColumnStarts', '#Legal Names for RFC Inland Outport Request Detail downloads'  
exec tp_property_comment 'excel.properties', 'XLContractLegalColumnStarts', '#Legal Names for Contract Detail downloads'  
exec tp_property_comment 'excel.properties', 'XLOFALegalColumnStarts', '#Legal Names for OFA downloads'  
exec tp_property_comment 'excel.properties', 'XLOFADetailLegalColumnStarts', '#Legal Names for OFA Detail downloads'  
exec tp_property_comment 'excel.properties', 'XLIOCARRIEROFAAirLegalColumnStarts', '# Leagal name column for Air OFA excel download'  
exec tp_property_comment 'excel.properties', 'XLAmendLegalColumnStarts', '#Legal Names for Amend Detail downloads'  
exec tp_property_comment 'excel.properties', 'XLConfigDefaultName', '### -----------------------------------------------------------------------\n###   ConfigRate Names for excel down loads.\n###------------------------------------------------------------------------'  
exec tp_property_comment 'excel.properties', 'XLAirSCRConfigRowStarts', '# Air Offer/Contract Search/Compare Results'  
exec tp_property_comment 'excel.properties', 'XLCarrierIOOFAConfigRowStarts', '# These variables are used in IOCarrierInitiatedOFAWriter.java'  
exec tp_property_comment 'excel.properties', 'XLMaxCsvExportTimeout', '#12 hrs time out (secs) set for Search/compare Export csv'  


-- Found file: optimdl.properties 


-- Found file: rate-overview-report.properties 


-- Found file: report.properties 


-- Found file: tradiant.properties 
exec tp_property_comment 'tradiant.properties', 'gtnexusSupportEmailAddress', '# E-mail address for GT Nexus support.\n# Production=support@gtnexus.com, QA=support@example.com'  
exec tp_property_comment 'tradiant.properties', 'useLegacyHelp', '# G2 Help Links\n# flip this on to turn on the legacy help system, default to false'  
exec tp_property_comment 'tradiant.properties', 'notificationFromEmailAddress', '# Production=notifications@gtnexus.com, QA=notifications@example.com'  
exec tp_property_comment 'tradiant.properties', 'notificationDisclaimer', '# Collaborative notification disclaimer'  
exec tp_property_comment 'tradiant.properties', 'isWhiteLabelingEnable', '# GPM only notification disclaimer\n#notificationDisclaimer=This message was generated automatically by GT Nexus based on \nyour notification preferences.'  
exec tp_property_comment 'tradiant.properties', 'notificationOn', '# Encrypted password for the evaluator user'  
exec tp_property_comment 'tradiant.properties', 'currencyUpdateTime', '# (mthyen) 2004-08-05 - changed to taskscheduler for 7.7 so no longer used\n# see planning.currency.task.start'  
exec tp_property_comment 'tradiant.properties', 'currencyUpdateInterval', '# (mthyen) 2004-08-05 - changed to taskscheduler for 7.7 so no longer used\n# see planning.currency.task.start'  
exec tp_property_comment 'tradiant.properties', 'currencyUpdateDatabase', '# (mthyen) 2004-08-05 - This appears to be used no longer and will be removed post 7.7'  
exec tp_property_comment 'tradiant.properties', 'currencyUpdateExcelTemplate', '# (mthyen) 2004-08-05 - This appears to be used no longer and will be removed post 7.7'  
exec tp_property_comment 'tradiant.properties', 'initTNE', '# initOfferExpiration=true'  
exec tp_property_comment 'tradiant.properties', 'initCleanupFrequency', '# minutes between cleanup of failed expirations (currenly 12 hours)'  
exec tp_property_comment 'tradiant.properties', 'xml310Url', '# doIEDoc=true'  
exec tp_property_comment 'tradiant.properties', 'createDivisionEmailAddress', '# Production=register@gtnexus.com, QA=register@example.com'  
exec tp_property_comment 'tradiant.properties', 'ubsVoyageCacheSize', '# Specifies the cache size for voyages.'  
exec tp_property_comment 'tradiant.properties', 'SQLInClauseMax', '# Specifies the maximum number of entries in a SQL IN clause.'  
exec tp_property_comment 'tradiant.properties', 'ubsShipperIntegration', '# Specifies whether shipper and carrier integration is turned on'  
exec tp_property_comment 'tradiant.properties', 'ubsAudit', '# Specified whether auditing is turned on'  
exec tp_property_comment 'tradiant.properties', 'initBookingService', '# Specifies if we want to audit booking schedules\n# Bug 34327 (jkuo): This process is not being monitored.\n#     Please consult me before turning it back on in the future.\n#     The backlog of data could cause extremely long SQL process time.'  
exec tp_property_comment 'tradiant.properties', 'SPNSupportEmailAddress', '# Tradiant e-mail address where important SPN related notifications should\n# be e-mailed to. This is currently used to notify when a shipper requests\n# to sign-up for SPN.\n# Production=support@gtnexus.com, QA=support@example.com'  
exec tp_property_comment 'tradiant.properties', 'initVMServices', '# Tells Weblogic to turn on the visibility manager\n# mailing, scanning, shipment expiration and sms services'  
exec tp_property_comment 'tradiant.properties', 'useTradDBConnection', '# If true, Connection objects will be instantiated as TradDBConnection\n# objects.  This is useful for debugging.'  
exec tp_property_comment 'tradiant.properties', 'appendStackTraceToSQL', '# If true, a stack trace will be appended, in comments, to SQL calls.\n# This only works if useTradDBConnection=true.  Useful for debugging and\n# SQL profiling.'  
exec tp_property_comment 'tradiant.properties', 'planningLineItemLimit', '# Please set to be equal to 1 mod 10: 101, 501, 1001 etc. The UI checks to see\n# if the number of returned rows is "number + 1" to determine if it will\n# display "1 - x of 1000+" or "1 - x of 1000".  This value affects components\n# in the app server AND the web container, so when changing it here, you need\n# to restart both.'  
exec tp_property_comment 'tradiant.properties', 'contractLineItemQueryTempTable', '# This is an optimization tweak for retrieving contract line items.  If true,\n# contract line item queries will SELECTed into a temp table, which is later\n# read for results.  If false, the queries will be UNIONed into one query.'  
exec tp_property_comment 'tradiant.properties', 'fmcAllowGPMToFileAmend', '# ALLOW GPM USER TO FILE\n# whether or not to allow the GPM user to file with the FMC'  
exec tp_property_comment 'tradiant.properties', 'fmcOrgId', '# FMC ACCOUNT ORG NUMBER, USER, AND PASSWORDS + FMC FILING SITE URL AND REALM\n# specifies the GPM Org's FMC id\n# **** gpm production: set to MOL org id'  
exec tp_property_comment 'tradiant.properties', 'fmcURL', '# specifies page where filing is done\n# **** production: set to production URL'  
exec tp_property_comment 'tradiant.properties', 'fmcRealm', '# specifies the fmc realm'  
exec tp_property_comment 'tradiant.properties', 'fmcSiteUser', '# user that can access the FMC site\n# **** production: set to James Galligan user'  
exec tp_property_comment 'tradiant.properties', 'fmcSiteUserPsswd', '# fmcSiteUser's password\n# **** production: set to James Galligan user's password'  
exec tp_property_comment 'tradiant.properties', 'fmcTest', '# FILING TO TEST ACCOUNT - NAMING OF TEST FILING FILES AND CONTRACTS\n# whether is a real filing or not - is the information real?\n# **** this should be set to "false" for production\n# WARNING: fmcTest setting only affects naming of files and contracts'  
exec tp_property_comment 'tradiant.properties', 'fmcFilePrefix', '# if filing with the FMC and fmcTest is false, this string will be prepended to the filename (for contracts and amendments)'  
exec tp_property_comment 'tradiant.properties', 'fmcFileTestPrefix', '# if filing with the FMC and fmcTest is true,  this string will be prepended to the filename (for contracts and amendments)'  
exec tp_property_comment 'tradiant.properties', 'fmcTestContractId', '# if fmcTest == true, then prepend the contract id with this String'  
exec tp_property_comment 'tradiant.properties', 'fmcProdTestOrgId', '# TEST FILING ON PRODUCTION\n# is allows testing of filing on production by the network host\n# always set these to the test filing account'  
exec tp_property_comment 'tradiant.properties', 'carrierPerfMsTypes', '###-----------------------------------------------------------------\n### For Orders, Carrier Performance Analytic Report (\n### See : com.tradiant.orders.ejb.analyticsmgr.CarrierPerformanceQuery.java\n### List of all standard milestone type ids that are used for calculating\n### Carrier performance.\n### ARRIVED(9),  DEPARTED(6),  DISCHARGED(10),     FULL_OUTGATE(16)\n### ON_RAIL(17), OFF_RAIL(18), TRUCK_DEPARTED(20), EMPTY_RETURNED(24)\n###-------------------------------------------------------------------------'  
exec tp_property_comment 'tradiant.properties', 'firstSecurityProviderName', '###-----------------------------------------------------------------\n### Security Providers\n###-----------------------------------------------------------------\n### these will set the System properties security.provider.1 and security.provider.2\n### in startup, replacing any settings that are in\n###    %JAVA_HOME%\jre\lib\security\java.security\n###\n### Note: These settings are NOT used for WebLogic 10. Change java.security instead.\n###\n### SUN = sun.security.provider.Sun\n### SunJSSE = com.sun.net.ssl.internal.ssl.Provider\n### SunJCE = sun.crypto.provider.SunJCE'  
exec tp_property_comment 'tradiant.properties', 'orgIdCacheExpirationTime', '### ------------------------------------------------------------------------\n### OrgCacheSettings\n### ------------------------------------------------------------------------\n# These values are set when OrgCache caches are first created and are not dynamic\n# Long time in milliseconds that OrgIdCache entries should remain in Cache'  
exec tp_property_comment 'tradiant.properties', 'orgSCACCacheExpirationTime', '# Long time in milliseconds that scacOrgIdMap entries should remain in Cache'  
exec tp_property_comment 'tradiant.properties', 'includedFF1inDoc', '### -----------------------------------------------------------------------------\n###  Flex Fields to Include in GPM Amendment Signature Pages and Formal Contracts\n### -----------------------------------------------------------------------------\n# includeFlexFieldsInGPMDocs=true'  
exec tp_property_comment 'tradiant.properties', 'KmlServerAddress', '# Google Map data file configurations\n# kml.dir needs to be set to physical path to a temp folder where kml cache file can be stored.\n# IMPORTANT: when deployed to load-balanced servers the directry name needs to be set to a shared\n# directory where all load-balanced server can access. ex: \\qamainapp1b\d$\apps\\apptemp\\kmlfiles\n# retentionMinutes is the number of minutes system caches the generated KML files. Default to 30 minutes\n# kmlServerAddress is the public accessible URL to the KML files on this server. for the QA machines the public IP addresses are:\n# QAMain1b: 72.44.208.200\n# QAtools1b: 72.44.208.201\n# QAStage1b: 72.44.208.202\n# QAFC1b: 72.44.208.203\n# For other public accessible servers like production or demo, we can use the actual domain names rather than IP addresses\n# IMPORTANT: pay attention to "http" vs. "https"'  
exec tp_property_comment 'tradiant.properties', 'KmlResourceUrl', '# kmlResourceUrl is the URL prefix to be embedded in the KML files that reference to images and other KML resources\n# before it is deployed to production keep it as "demo.gtnexus.com"'  
exec tp_property_comment 'tradiant.properties', 'initIntegrationPropertiesCache', '# integration.properties cache'  
exec tp_property_comment 'tradiant.properties', 'autoOnboardSupplierAfterRegistration', '#Bug 46976 - Auto onboard through registration.'  
